websign/models/Button.php
<?php


namespace app\models;
use yii\db\ActiveRecord;

class Button extends ActiveRecord {


    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }



    public static function tableName(){
        return 'button';
    }
    public function getAllEvents()
    {
        return $this->hasMany(AllEvent::className(), ['button_id' => 'id']);
    }
}

websign/controllers/ButtonController.php
<?php


namespace app\controllers;

use app\models\Button;
use app\models\AllEvent;
use Yii;
use yii\data\Pagination;


class ButtonController extends AppController {
    public function actionIndex() {
        $this->setMeta('SOFT');
        return $this->render('index');
    }
    public function actionView($id){
        $id = Yii::$app->request->get('id');

//        $events = AllEvent::find()->where(['button_id'=>$id])->all();

        //pagination
        $query =AllEvent::find()->where(['button_id'=>$id]);
        $pages = new Pagination(['totalCount'=>$query->count(),'pageSize' => 3,
            //додаткові параметри для відображення адреси в браузері
            'forcePageParam' => false,'pageSizeParam' => false]);
        $events = $query->offset($pages->offset)->limit($pages->limit)->all();

        $button = Button::findOne($id);

        $this->setMeta('SOFT | ' . $button->name,$button->keywords, $button->description);

        return $this->render('view', compact('events','button','pages'));

    }

}

websign/controllers/MyeventController.php
<?php


namespace app\controllers;
use app\models\Button;
use app\models\AllEvent;
use Yii;
use yii\web\HttpException;

class MyeventController extends AppController {
    public function actionView($id){
        //наш івент або з параметру public function actionView($id)
//        $id =Yii::$app->request->get('id');
        //лінива
        $event = AllEvent::findOne($id);
        //жадібна
//        $event = MyEvent::find()->with('category')->where(['id'=>$id])->limit(1)->one();
        //----------------------
        if(empty($event))
            throw new HttpException(404,'Такого івенту немає');
        //----------------------
        //відкриті заходи
//        $opens = AllEvent::find()->where(['open'=>'1'])->limit(6)->all();
        //meta
        $this->setMeta('SOFT | '. $event->name,$event->keywords,
            $event->description);

        return $this->render('view',compact('event'));


    }

}

websign/controllers/PartController.php
<?php

namespace app\controllers;
use app\models\AllEvent;
use app\models\Part;
use Yii;
use app\models\EventRegister;
use app\models\EventRegisterItems;
use yii\db\Exception;


class PartController extends AppController {
    public function actionAdd(){
        $id = Yii::$app->request->get('id');
//        debug($id);

        $event =ALLEvent::findOne($id);
        if(empty($event))return false;
//        debug($event);
        $session=Yii::$app->session;
        $session->open();
        $part =new Part();
        $part->addToPart($event);
//        debug($session['part']);

        //Якщо запит не Ajax
        if(!Yii::$app->request->isAjax ){
            //вертаємось на туж сторінку
            return $this->redirect(Yii::$app->request->referrer);
        }
//
        //прибераумо шаблон
        $this->layout=false;
        return $this->render('part-modal',compact('session'));
    }
    public function actionClear(){
        $session=Yii::$app->session;
        $session->open();
        $session->remove('part');

        $this->layout=false;
        return $this->render('part-modal',compact('session'));
    }
    public function actionDelItem(){
        $id = Yii::$app->request->get('id');
        $session=Yii::$app->session;
        $session->open();
        $part = new Part();
        $part->rewrite($id);
        $this->layout=false;
        return $this->render('part-modal',compact('session'));
    }
    public function actionShow(){
        $session=Yii::$app->session;
        $session->open();
        $this->layout=false;
        return $this->render('part-modal',compact('session'));
    }
    public function actionView(){
        $session=Yii::$app->session;
        $session->open();
        $this->setMeta("SOFT | Реєстрація");
        $eventregister = new EventRegister();
        //приймаємо дані
        if ($eventregister->load(Yii::$app->request->post())){
//            debug(Yii::$app->request->post());
            //заносимо дані в таблицю

            $eventregister->count_part = count($session['part']);
            if($eventregister->save()) {
                $this->saveEventRegisterItems($session['part'], $eventregister->id);
///////////////////////////////////////////////////////////////////////
                $number =$eventregister->id;
//debug($session );


                //flash повідомлення
                Yii::$app->session->setFlash('success', 'Ваша заявка прийнята,
                     номер реєстрації :' . "<h1>$number</h1>");


//                // відправляємо листа
                Yii::$app->mailer->compose('layouts/register', ['session' => $session,'number'=>$number])
                    ->setFrom(['semyonov.mychayl@gmail.com' => 'SOFT'])
                    ->setTo($eventregister->email)
                    ->setSubject('Peєстрація на сервісі SOFT')
                    ->send();
                $session->remove('part');

                return $this->refresh();

            }else{
                Yii::$app->session->setFlash('error','Помилка оформлення заявки на участь');
            }
        }
        return $this->render('view', compact('session','eventregister'));
    }
    protected function saveEventRegisterItems($items, $eventregister_id){
        foreach ($items as $id=>$item){
            $eventeregister_items = new EventRegisterItems();
            $eventeregister_items->event_register_id = $eventregister_id;
            $eventeregister_items->event_id = $id;
            $eventeregister_items->name = $item['name'];

            $eventeregister_items->save();

        }
    }
}

websign/views/button/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;


use app\components\ButtonWidget; ?>



<section>


    <div class="background">
        <article>
            <?= ButtonWidget::widget(['tpl'=>'menu'])?>
        </article>

    </div>







</section>

websign/views/button/view.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\LinkPager;


use app\components\ButtonWidget;
?>

<section id="advertisement">
    <div class="container">
        <img src="/images/shop/advertisement.jpg" alt="" />
    </div>
</section>

<section>
    <div class="container">
        <div class="row">


            <div class="col-sm-12 padding-right">
                <div class="features_items"><!--features_items-->

                    <h2 class="title text-center"><?= $button->name?></h2>

                        <?php if(!empty($events)): ?>
                            <?php  $i=0; foreach ($events as $event): ?>
                                <div class="col-sm-4"></div>
                            <div class="col-sm-4">
                                <div class="product-image-wrapper">
                                    <div class="single-products">
                                        <div class="productinfo text-center">

                                            <?= Html::img("@web/images/events-foto/{$event->img}",['alt'=>$event->name]) ?>

                                            <h2><a href="<?= Url::to(['myevent/view','id'=>$event->id])?>"><?= $event->name ?></a></h2>
                                            <a href="<?= Url::to(['part/add','id'=>$event->id]) ?>" data-id="<?= $event->id ?>"
                                               class="btn btn-default add-to-cart">
                                                <i class="fa fa-shopping-cart"></i>Прийняти участь</a>
                                        </div>

                                    </div>

                                </div>
                            </div>


                            <?php if($i%3==0): ?>
                                <div class="clearfix" ></div>
                            <?php endif; ?>
                        <?php endforeach;?>
                        <div class="clearfix" ></div>
                            <?php
                        echo LinkPager::widget(['pagination' => $pages,])
                                ?>
                    <?php else:?>
                        <h2 id="no-ivent">Івентів немає!!!</h2>
                    <?php endif; ?>



                </div><!--features_items-->
            </div>
        </div>
    </div>
</section>