websign/controllers/PartController.php
<?php

namespace app\controllers;
use app\models\AllEvent;
use app\models\Part;
use Yii;
use app\models\EventRegister;
use app\models\EventRegisterItems;
use yii\db\Exception;


class PartController extends AppController {
    public function actionAdd(){
        $id = Yii::$app->request->get('id');
//        debug($id);

        $event =ALLEvent::findOne($id);
        if(empty($event))return false;
//        debug($event);
        $session=Yii::$app->session;
        $session->open();
        $part =new Part();
        $part->addToPart($event);
//        debug($session['part']);

        //Якщо запит не Ajax
        if(!Yii::$app->request->isAjax ){
            //вертаємось на туж сторінку
            return $this->redirect(Yii::$app->request->referrer);
        }
//
        //прибераумо шаблон
        $this->layout=false;
        return $this->render('part-modal',compact('session'));
    }
    public function actionClear(){
        $session=Yii::$app->session;
        $session->open();
        $session->remove('part');

        $this->layout=false;
        return $this->render('part-modal',compact('session'));
    }
    public function actionDelItem(){
        $id = Yii::$app->request->get('id');
        $session=Yii::$app->session;
        $session->open();
        $part = new Part();
        $part->rewrite($id);
        $this->layout=false;
        return $this->render('part-modal',compact('session'));
    }
    public function actionShow(){
        $session=Yii::$app->session;
        $session->open();
        $this->layout=false;
        return $this->render('part-modal',compact('session'));
    }
    public function actionView(){
        $session=Yii::$app->session;
        $session->open();
        $this->setMeta("SOFT | Реєстрація");
        $eventregister = new EventRegister();
        //приймаємо дані
        if ($eventregister->load(Yii::$app->request->post())){
//            debug(Yii::$app->request->post());
            //заносимо дані в таблицю

            $eventregister->count_part = count($session['part']);
            if($eventregister->save()) {
                $this->saveEventRegisterItems($session['part'], $eventregister->id);
///////////////////////////////////////////////////////////////////////
                $number =$eventregister->id;
//debug($session );


                //flash повідомлення
                Yii::$app->session->setFlash('success', 'Ваша заявка прийнята,
                     номер реєстрації :' . "<h1>$number</h1>");


//                // відправляємо листа
                Yii::$app->mailer->compose('layouts/register', ['session' => $session,'number'=>$number])
                    ->setFrom(['semyonov.mychayl@gmail.com' => 'SOFT'])
                    ->setTo($eventregister->email)
                    ->setSubject('Peєстрація на сервісі SOFT')
                    ->send();
                $session->remove('part');

                return $this->refresh();

            }else{
                Yii::$app->session->setFlash('error','Помилка оформлення заявки на участь');
            }
        }
        return $this->render('view', compact('session','eventregister'));
    }
    protected function saveEventRegisterItems($items, $eventregister_id){
        foreach ($items as $id=>$item){
            $eventeregister_items = new EventRegisterItems();
            $eventeregister_items->event_register_id = $eventregister_id;
            $eventeregister_items->event_id = $id;
            $eventeregister_items->name = $item['name'];

            $eventeregister_items->save();

        }
    }
}

websign/views/layouts/_main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

websign/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */


use app\widgets\Alert;
use \yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <?php $this->registerLinkTag([
        'rel' => 'shortcut icon',
        'type' => 'image/x-icon',
        'href' => '/web/images/favicon_s.ico',
    ]);?>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>

    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
<?php $this->beginBody() ?>
<header id="header"><!--header-->
    <div class="header_top"><!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="#"><i class="fa fa-phone"></i> +38 098 245 87 37 </a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> semyonov.mychayl@gmail.com</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->

    <div class="header-middle"><!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="logo pull-left">
                        <a href="<?= Url::home()?>"><?= Html::img('@web/images/home/logo_soft.png', ['alt'=>'SOFT'])?></a>
                    </div>

                </div>
                <div class="col-sm-8">
                    <div class="shop-menu pull-right">
                        <ul class="nav navbar-nav">
                            <?php if(!Yii::$app->user->isGuest): ?>
                                <li><a href="<?= Url::to(['/site/logout'])?>"><i class="fa fa-user"></i>
                                        <?= Yii::$app->user->identity['username']?>(Вихід)</a></li>
                            <?php endif;?>
                            <li class="getPart"><a href="#" onclick ="return getPart()"><i class="fa fa-shopping-cart getPart"></i> Корзина</a></li>
                            <li><a  href="<?= Url::to(['/part/view'])?>"><i class="fa fa-check getPart"></i>Реєстрація</a></li>
                            <li><a href="<?= Url::to(['/admin'])?>"><i class="fa fa-lock"></i> Login</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom"><!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <li><a href="<?= Url::home()?>" class="active">Home</a></li>

                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

<?= $content;?>

<footer id="footer"><!--Footer-->

    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <p class="pull-left">Copyright © 2020 ZHYTOMYR POLYTECHNIC Inc. All rights reserved.</p>
                <p class="pull-right">Designed by <span><a >Semenov M. V.</a></span></p>
            </div>
        </div>
    </div>

</footer><!--/Footer-->

<?php
Modal::begin([
    'header' => '<h2>Реєстрація</h2>',
    'id' => 'partModal',
//    'size' => 'modal-lg',
    'footer' => ' <a class="btn btn-default update" data-dismiss="modal" href="#">Продовжити</a>
                 <a href=" '. Url::to(['part/view']) .'" class="btn btn-default check_out " >Оформити реєстрацію</a>
     <button type="button" class="btn btn-default check_out clearRegister">Очистити все</button>'
]);
Modal::end();
?>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>